channel_id:
  - UCUyeluBRhGPCW4rPe_UvBZQ # ThePrimeTime
  - UCd3dNckv1Za2coSaHGHl5aA # TJ DeVries
  - UCSHZKyawb77ixDdsGog4iWA # Lex Fridman
  - UC9x0AN7BWHpCDHSm9NiJFJQ # NetworkChuck
language: en
request_timeout: 60
chunk_size: 500
chunk_overlap: 50
embedding_size: 1024
embedding_model_name: bge-large
embeddig_num_ctx: 512
index_hnsm_m: 16
index_hnsm_ef_construction: 64
index_hnsm_ef_searh: 40
index_vector_ops: l2
results_to_retrieve: 5
rerank_model_name: rank-T5-flan
rerank_score_threshold: 0.1
chat_model_name: llama3.2:3b
chat_temperature: 0.1
chat_max_tokens: 500
